### ISSUE TITLE
Can't stop retrying and clear .deploytmp when stop by Ctrl + C

### ISSUE THREAD

**Issue by xpader** [dg/ftp-deployment#145]
Version: 3.4.0

When use Ctrl + C to stop uploading, the retrying will always run and can't stop it, we need use Ctrl + C a lot of times to stop it.
And the .deploytmp file will stay in ftp server..

**Comment by xpader** [comment]
Try to stop process before fully upload file to ftp sites complete.

The problem one is you can't stop uploading progress when you just type once Ctrl + C.
The problem two is when you stopped uploading progress by type Ctrl +C many times, every xxx.deploytmp files will leave in ftp server.

I think we need clean xxx.deploytmp files when stop the uploading progress.

**Comment by dg** [comment]
> The problem one is you can't stop uploading progress when you just type once Ctrl + C.

That's I can't replicate…

> The problem two is when you stopped uploading progress by type Ctrl +C, every xxx.deploytmp files will leave in ftp server.

I tried to implement it 2aff6975e59dc5c8561cd8465cd840c8d5a02bc3

**Comment by Pryx** [comment]
I have recently updated from some old-ish version of ftp-deployment to 3.5.1 and can confirm that I cannot easily stop the script using Ctrl + C. I am running the script on Linux so that might be a factor - when I press Ctrl + C I am getting this error message:

```
Error: Deployment\ServerException: Interrupted system call in deployment.phar/src/Deployment/FtpServer.php:2
```

Seems like interrupts should be handled differently from other exceptions so that the script doesn't retry the upload when it should be shutting down. The easiest way to handle this on Linux would probably be to check for `EINTR` somewhere in https://github.com/dg/ftp-deployment/blob/190d610fedffc09fb62b8e8e23640b0210024db5/src/Deployment/Safe.php#L66-L75 and just not retry in that case. But AFAIK we cannot get the reason for `EINTR` so this does not seem to be the correct solution.

A much better and probably the most correct way would be to register a signal handler using `pcntl_signal` which would be stopping the upload and running the cleanup when `SIGINT`/`SIGTERM` is called. 

I can implement it and make a PR if you wish.

**Comment by dg** [comment]
Oh, that's it. I use Windows and I have never tested Linux.  

Could you try this? This is used in Nette Tester  0b4a2388bbce7eaa37a584e0f3461abfb4b14968

**Comment by Pryx** [comment]
Didn't know PHP had `pcntl_async_signals`, but I didn't work on any PHP CLI scripts for quite some time :slightly_smiling_face:  

Seems like this fixed the problem. One issue I notice is that when running the cleanup, sometimes it gets stuck and I have to press CTRL + C again. Seems that the problem occurs when uploading a file and stopping the script before the upload is complete. It is only noticeable when uploading larger files though, so not much of an issue. 

But the original problem is definitely fixed and the script actually stops now, thanks :+1:

**Comment by dg** [comment]
Great
