### ISSUE TITLE
Unable to upload to root directory

### ISSUE THREAD

**Issue by Valicek1** [dg/ftp-deployment#44]
Hi, 
thank you for nice tool, works almost perfectly. I have only one (maybe) bug. When I try to upload to root of FTP (remote = ftp://user:pass@server.tld/), script falls down with message:

Error: /folder/ není souborem ani adresářem

When I try to upload to some subfolder, there is no problem. I have tried adding or removing trailing slash, but withou success. Until now, I was using this amazing tool for uploads to my prod. server, there was no need to upload to root of ftp... But now I'm maintaining 3rd party site and this is required... Is it bug or did I have overlooked something? I'm using linux (Debian Jessie, i386, PHP 5.6.0RC2)

**Comment by hranicka** [comment]
@dg I've problem with deploy after your revert.

I get same results as described above.
It's NOT OK also when I set root path `/` instead of nothing (empty string).

When i revert this revert, everything works fine.

Can you revert your revert of the fix please?

**Comment by dg** [comment]
I realized that patch was wrong, because it leads to doubled `/` on many places ([here](https://github.com/dg/ftp-deployment/blob/47f638cff14c57c27a9504f400ce24d83ca6cdc6/Deployment/libs/Deployer.php#L193) or [here](https://github.com/dg/ftp-deployment/blob/47f638cff14c57c27a9504f400ce24d83ca6cdc6/Deployment/libs/Deployer.php#L233). 

Or behaves it differently for you?

**Comment by hranicka** [comment]
You're right. Leading `/` is doubled. But it worked, now deploy fails.

Should I realize the new patch for that? (if @dg or @Valicek1 are not working on it)

**Comment by dg** [comment]
I am not able to simulate this state, so I don't know where problem is. Can you find it out?
