### ISSUE TITLE
'Error: ssh2_sftp_mkdir failures.' when trying to upload to sftp

### ISSUE THREAD

**Issue by tmsbrg** [dg/ftp-deployment#87]
Hey, I'm getting this error when trying to use ftp-deployment to upload to my website's SFTP server. I tested uploading with the `sftp` CLI client and it showed that sftp itself is working. The server's probably configured in a way ftp-deployment isn't expecting. I'm using the latest (Github) version of ftp-deployment. I'm puzzled by it. Here are my config file and outlog log:
## _deployment.ini:

```
log = _deployment.log

remote = sftp://USERNAME:PASSWORD@URL

local = ./_site

preprocess = no

ignore = "misc"
```

---
## _deployment.log:

```
Started at [2016/09/24 15:28]
Config file is { DIRECTORY }/_deployment.ini

Deploying 
Live mode
Connecting to server
Remote .htdeployment file not found
Scanning files in  { DIRECTORY }/_site
Creating remote file .htdeployment.running
Error: ssh2_sftp_mkdir failures.

Deployment\SshException: ssh2_sftp_mkdir failures. in  { DIRECTORY }/ftp-deployment/src/Deployment/SshServer.php:226
Stack trace:
#0  { DIRECTORY }/ftp-deployment/src/Deployment/SshServer.php(132): Deployment\SshServer->protect('ssh2_sftp_mkdir', Array)
#1  { DIRECTORY }/ftp-deployment/src/Deployment/Deployer.php(139): Deployment\SshServer->createDir('/')
#2  { DIRECTORY }/ftp-deployment/src/Deployment/CliRunner.php(93): Deployment\Deployer->deploy()
#3  { DIRECTORY }/ftp-deployment/src/deployment.php(22): Deployment\CliRunner->run()
#4  { DIRECTORY }/ftp-deployment/deployment(3): require(' { DIRECTORY }...')
#5 {main}
```

---

I tried uncommenting line 139 in Deployer.php (maybe ftp-deployment thinks it can create directories which already exist, while the server doesn't like that?) and got a different error:
## _deployment.log:

```
Started at [2016/09/24 15:43]
Config file is { DIRECTORY }/_deployment.ini

Deploying 
Live mode
Connecting to server
Remote .htdeployment file not found
Scanning files in  { DIRECTORY }/_site
Creating remote file .htdeployment.running
Error: fwrite() expects parameter 1 to be resource, boolean given

Deployment\SshException: fwrite() expects parameter 1 to be resource, boolean given in { DIRECTORY }/ftp-deployment/src/Deployment/SshServer.php:224
Stack trace:
#0 { DIRECTORY }/ftp-deployment/src/Deployment/SshServer.php(92): Deployment\SshServer->protect(Object(Closure))
#1{ DIRECTORY }/ftp-deployment/src/Deployment/Deployer.php(140): Deployment\SshServer->writeFile('/tmp/deployment...', '/.htdeployment....')
#2 { DIRECTORY }/ftp-deployment/src/Deployment/CliRunner.php(93): Deployment\Deployer->deploy()
#3 { DIRECTORY }/ftp-deployment/src/deployment.php(22): Deployment\CliRunner->run()
#4 { DIRECTORY }/ftp-deployment/deployment(3): require('{ DIRECTORY }...')
#5 {main}
```

---

Is there anything you see that could be the obvious cause? I'm willing to look into it myself but I don't know the code as well and I'm a bit stumped currently. It's quite important to me because I used ftp-deployment to easily update my site whenever I changed it (it's great!), and doing it manually in sftp is such a pain it's really not doable.

**Comment by dg** [comment]
It seems that ssh2-sftp http://php.net/manual/en/function.ssh2-sftp.php doesn't work. 

Can you try dump `$this->sftp` after line 58? (`$this->sftp = ssh2_sftp($this->connection);`).

**Comment by tmsbrg** [comment]
I assume you mean this (I'm not really a PHP programmer):
`			var_dump($this->sftp = ssh2_sftp($this->connection));`
Doing that indeed shows me the value is `bool(false)`, so it's not connecting.

Reminds me I only have SFTP access to the machine, it's configured not to allow regular SSH access. Maybe ssh2_sftp assumes it can access through regular SSH and open a shell, which the server denies? That seems likely. Even more likely looking at this part of the manual for ssh2_sftp:
```
session

    An SSH connection link identifier, obtained from a call to ssh2_connect().
```
Likely ssh2_connect fails for me. The solution would be using a different SFTP backend or maybe if it's possible configure ssh2_sftp to work with these conditions.

**Comment by tmsbrg** [comment]
Alright, I installed php-phpseclib and made this:

```php
<?php
include 'phpseclib/autoload.php';
 
$sftp = new \phpseclib\Net\SFTP('URL');
if (!$sftp->login('USERNAME', 'PASSWORD')) {
  exit('Login Failed');
}
$sftp->put('testy.txt', 'hello, world!');
echo $sftp->pwd() . "\r\n";
print_r($sftp->nlist());

?>
```

And it works! It adds the text file and prints out the home directory files.

**Comment by dg** [comment]
> Likely ssh2_connect fails for me

It surprises me that it didn't trigger error… Can you try the lastest version?

**Comment by tmsbrg** [comment]
Weirdly, I can't reproduce this anymore:
>`var_dump($this->sftp = ssh2_sftp($this->connection));`
>Doing that indeed shows me the value is bool(false), so it's not connecting.

Maybe I did something wrong but it's hard to imagine for me how I did that wrong. Anyway, checking `var_dump` on the `$this->sftp` now gives me `resource(19) of type (SSH2 SFTP)`. This is both on the version I originally reported this on and on the latest version. So the ssh2_sftp function isn't giving an error, only when actually doing something with mkdir does it give an error. Mysterious.

**Comment by dg** [comment]
So it still doesn't work?

**Comment by tmsbrg** [comment]
Yes, it still doesn't work, but it doesn't return an error when initializing. The error it breaks on is exactly the same as before, as I showed in my first _deployment.log. It's weird that it doesn't seem to give an error earlier.

**Comment by ne0-cz** [comment]
I'm using the official ssh2 PECL extension 1.0 alpha on Linux.

After upgrading PHP 7.0.12 to 7.0.13, this issue appeared (I'm using key-based login via ssh-agent). After downgrading to 7.0.12, everything works fine again.

What's your PHP version?

**Comment by tmsbrg** [comment]
I'm using the standard version in Ubuntu 16.04: 7.0.8-0ubuntu0.16.04.3

**Comment by tmsbrg** [comment]
Now it just errors on this (below). It's probably still the same weirdness with SSH. Thanks for looking into it though. I might look into alternative ways to solve the problem if I have time. phpseclib still seems like the thing that works right now, though I understand you don't want to maintain two implementations of SFTP. I'm thinking of just writing a small personal script specially for my use case.

```
Deploying         
Live mode        
Connecting to server        
Remote .htdeployment file not found        
Scanning files in {DIR}        
Creating remote file .htdeployment.running        
Error: Unable to open ssh2.sftp://Resource id #19/.htdeployment.running on remote host
```

**Comment by adamkudrna** [comment]
I'm also experiencing this using version 2.7, both on PHP 7.0.14 and 7.1.0, ssh2 module version 1.0, Mac OS X 10.11.6. (I use our [GPG wrapper](https://github.com/visionappscz/gpg-ftp-deployment) for ftp-deployment but it should not matter.)

```bash
Deploying …
Live mode
Connecting to server
Remote .htdeployment file not found
Scanning files in …
…
Creating remote file .htdeployment.running
Error: ssh2_sftp_mkdir failures.

Deployment\SshException: ssh2_sftp_mkdir failures. in /Users/Adam/Web/gpg-ftp-deployment/vendor/dg/ftp-deployment/src/Deployment/SshServer.php:233
Stack trace:
#0 /Users/Adam/Web/gpg-ftp-deployment/vendor/dg/ftp-deployment/src/Deployment/SshServer.php(137): Deployment\SshServer->protect('ssh2_sftp_mkdir', Array)
#1 /Users/Adam/Web/gpg-ftp-deployment/vendor/dg/ftp-deployment/src/Deployment/Deployer.php(137): Deployment\SshServer->createDir('/home/synergicp...')
#2 /Users/Adam/Web/gpg-ftp-deployment/vendor/dg/ftp-deployment/src/Deployment/CliRunner.php(94): Deployment\Deployer->deploy()
#3 /Users/Adam/Web/gpg-ftp-deployment/vendor/dg/ftp-deployment/src/deployment.php(23): Deployment\CliRunner->run()
#4 {main}
```

**Comment by ne0-cz** [comment]
@tmsbrg It's strange that this problem appears with PHP 7.0.8, but maybe you should try the solution below:

@adamkudrna There's bug in the ssh2 1.0 module with PHP 7.0.13 and greater when using wrappers. The problem is not with the ssh2_sftp_mkdir - this returns false because it's called on a directory which exists. Error occurs with the `!file_exists("ssh2.sftp://$this->sftp$dir")` - since all ssh2.:// wrappers don't work, this will falsely say that the file does not exist.

See https://bugs.php.net/bug.php?id=71376 for bugreport, There's already commit which fixes it - http://git.php.net/?p=pecl/networking/ssh2.git;a=commit;h=17680cf039f0cfac53b5a2531fdb715b95e9cc42 - I haven't find a way to install unreleased extension via PECL, but you can compile and install the module manually: http://php.net/manual/de/install.pecl.phpize.php

@dg Since you provide compiled .dll extensions with every release, would you be so kind to provide which version (or commit) of the module are you using? (I guess you must be using the one which has this problem fixed since you seem you can't reproduce the bug and probably tested it with PHP 7.1.)

**Comment by dg** [comment]
I found binaries somewhere on https://www.apachelounge.com.

**Comment by ne0-cz** [comment]
OK, there's yet another bug in ssh2 module - https://bugs.php.net/bug.php?id=73600 - see the attached test case there (at the bottom right now), mere call to `stream_get_contents` segfaults the module!

I really think this issue is related to SSH2 module and not to ftp-deployment. Can @tmsbrg agree?

@adamkudrna The only solution I can recommend right now is downgrade to PHP 7.0.12.

@dg Would you reconsider https://github.com/dg/ftp-deployment/issues/68 (or should I move the discussion there?). The state of the SSH2 module is IMHO crazy, no reaction at the bug report for two months, I doubt any of the developers actually use the module with newer PHP. But I understand that it works for you and this is just your personal project so you might not really care that much (as opposed to some problem like that in Nette for example). TY anyway!

**Comment by dg** [comment]
@ne0-cz If phpseclib/phpseclib is the solution for these problems, I'm not against it.

**Comment by tmsbrg** [comment]
@ne0-cz I agree it's a bug with the SSH2 module. I also agree with using phpseclib to solve it. Is anyone willing to work on this? If not I can but I won't have time immediately. And note I'm not a PHP pro but I can learn it along the way. Also questions in #68 apply.

**Comment by ne0-cz** [comment]
@tmsbrg I'll probably try to work on this during weekend. It shouldn't be that hard I guess, we'll see :)

**Comment by ne0-cz** [comment]
OMG!

phpseclib/phpseclib does not support https://en.wikipedia.org/wiki/EdDSA#Ed25519 - the whole aim of the project is "pure PHP implementations of SSH, SFTP, RSA and X.509".

The SSH2 module relies on the https://libssh2.org/ so this kind of thing is handled by the SSH team.

I no longer think that using the phpseclib/phpseclib is a great idea; it would cause BC-break for people using SSH agent and Ed25519 keys (I do) with no workaround.

Should I open a new issue, or is it OK to discuss it here (it is kinda off-topic)?

My code so far is not really anything worth commiting - I've reimplemented just the `connect()` function and even the includes of the phpseclib are hackish at the moment.

There is an open issue at the phpseclib with this: https://github.com/phpseclib/phpseclib/issues/1082 - but I'm not sure what other things might break because they are not implemented in phpseclib (and I'm not really an SSH or security guru).

What do you think @dg? There could probably be two implementations of SshServer with some config value "usePhpseclib" so the new way would be optional without any BC-breaks. Or we could stick with the SSH2 module and hope that the maintainers will resolve their issues in some timely manner. I just don't know :(

**Comment by arron0** [comment]
BTW. I can reproduce this error also with PHP 5.6.30

**Comment by jirsbek** [comment]
Same problem here. PHP 5.6.29, libssh2 1.8.0, installed on macOS with pecl (ssh2-0.13).

Strangest is deploymen was working at the morning and now suddenly having the same issue.

**Comment by dg** [comment]
Hi, @BigMichi1 implemented phpseclib. Just use `phpsec://` protocol in `remote`. Can you try it? Did that solve the problem?
